set nocompatible

" options
set autoindent
set autoread
set autowrite
set background=light
set backspace=indent,eol,start
set encoding=utf-8
set expandtab
set fileformats=unix,dos,mac
set history=100
set hlsearch
set ignorecase
set incsearch
set list
set listchars=tab:>-,eol:$,trail:.,extends:>,precedes:<,nbsp:%
set number
set ruler
set shiftwidth=4
set shortmess+=I
set showbreak=+\ " don't delete
set showmatch
set smartcase
set smarttab
set softtabstop=4
set tabstop=8
set undolevels=1000
set wrap
set wrapscan
